### ISSUE TITLE
Not obvious how to start a game

### ISSUE THREAD

**Issue by seb128** [filip-dobrocky/2048#1] opened 2015-02-12 09:58 UTC
Using version 0.2 on current ubuntu touch, when starting the game for the first time you are welcomed with an empty grid, clicking around does nothing. To start the game you need to click the "refresh" icon on the top bar, that's not really obvious. It would be nice if the game would run directly with a new game, or showing a control over the grid "click here to start a game"

**Comment by filip-dobrocky** [comment] 2015-02-12 11:47
This seems to be a bug caused by an update of the ubuntu toolkit. A new game should be started automatically, at least that's how it worked before. I haven't looked at the app for a long time, but i should now that ubuntu for phones is starting to gain users. I'm glad you reported it.

**Comment by filip-dobrocky** [comment] 2015-02-15 12:14
Fixed now (I hope). It was an error in an "if statement" that happens at the start of the app.

**Closed as completed by filip-dobrocky** 2015-02-15 12:14 UTC
Labels: bug

**Comment by seb128** [comment] 2015-02-16 10:43
Great, do you plan to push an update to the store?

**Comment by filip-dobrocky** [comment] 2015-02-16 12:37
I already did yesterday (version 0.2.1). Nothing's really changed except that one line of code. It would be great if you could give me feedback if it works. But I tested it through the emulator, so it should be alright. Also, if you've got any other ideas to make the app better, feel free to open another issue.

**Comment by seb128** [comment] 2015-02-16 12:59
Oh, indeed, sorry I picked 2048 instead of 2048native while looking, the
second one has indeed an update and fixes the first start issue ;-)

**Comment by filip-dobrocky** [comment] 2015-02-16 13:30
Thanks for the feedback :)
